"""AUTOGENERATED from doxa/query/evaluator.py during refactoring."""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import (
    Any,
    Dict,
    List,
    Mapping,
    Sequence,
    Set,
    Tuple,
)

from doxa.core import LiteralType, TermKind
from doxa.core.belief_record import (
    BeliefArg,
    BeliefEntityArg,
    BeliefLiteralArg,
    BeliefRecord,
)
from doxa.core.goal import AssumeGoal, VarArg
from doxa.core.query import Query, QueryFocus
from doxa.query._epistemic import _aggregate_values, _derive_belnap_status
from doxa.query._types import (
    Subst,
    _AssumeGoal,
    _EvidenceRow,
    _Goal,
    _TruthRow,
)
from doxa.query._unification import _resolve
from doxa.query.engine import (
    QueryAnswer,
)
from doxa.query.postprocess import apply_focus, sort_answers

# ---------------------------------------------------------------------------
# Answer shaping
# ---------------------------------------------------------------------------


def _query_var_names(query: Query) -> Set[str]:
    names: Set[str] = set()
    for goal in query.goals:
        if isinstance(goal, AssumeGoal):
            for assumption in goal.assumptions:
                for arg in assumption.goal_args:
                    if isinstance(arg, VarArg):
                        names.add(arg.var.name)
        else:
            args = getattr(goal, "goal_args", [])
            for arg in args:
                if isinstance(arg, VarArg):
                    names.add(arg.var.name)
    return names - query.anon_vars


def _project_bindings(
    subst: Mapping[str, Any], vars_to_keep: Set[str]
) -> Dict[str, Any]:
    return {k: v for k, v in subst.items() if k in vars_to_keep}


def _inject_assume_facts(
    compiled_goals: Sequence[_Goal],
    fact_index: Dict[Tuple[str, int], List[BeliefRecord]],
    subst: Subst,
) -> None:
    """Inject temporary BeliefRecords for all explicit assume(...) goals.

    Mutates *fact_index* in place.  Only ground arguments (after applying
    *subst*) are injected; variable positions that remain unbound are
    silently skipped (the assumption is incomplete and cannot be injected).
    """
    from doxa.core.base_kinds import BaseKind

    for goal in compiled_goals:
        if not isinstance(goal, _AssumeGoal):
            continue
        for atom in goal.atoms:
            belief_args: list[BeliefArg] = []
            all_ground = True
            for arg in atom.args:
                val = _resolve(arg, subst)
                if val is None:
                    all_ground = False
                    break
                if isinstance(val, datetime):
                    belief_args.append(
                        BeliefLiteralArg(
                            kind=BaseKind.belief_arg,
                            term_kind=TermKind.lit,
                            lit_type=LiteralType.datetime,
                            value=val,
                        )
                    )
                elif isinstance(val, date):
                    belief_args.append(
                        BeliefLiteralArg(
                            kind=BaseKind.belief_arg,
                            term_kind=TermKind.lit,
                            lit_type=LiteralType.date,
                            value=val,
                        )
                    )
                elif isinstance(val, timedelta):
                    belief_args.append(
                        BeliefLiteralArg(
                            kind=BaseKind.belief_arg,
                            term_kind=TermKind.lit,
                            lit_type=LiteralType.duration,
                            value=val,
                        )
                    )
                elif isinstance(val, int):
                    belief_args.append(
                        BeliefLiteralArg(
                            kind=BaseKind.belief_arg,
                            term_kind=TermKind.lit,
                            lit_type=LiteralType.int,
                            value=val,
                        )
                    )
                elif isinstance(val, float):
                    belief_args.append(
                        BeliefLiteralArg(
                            kind=BaseKind.belief_arg,
                            term_kind=TermKind.lit,
                            lit_type=LiteralType.float,
                            value=val,
                        )
                    )
                else:
                    belief_args.append(
                        BeliefEntityArg(
                            kind=BaseKind.belief_arg,
                            term_kind="ent",
                            ent_name=str(val),
                        )
                    )

            if not all_ground:
                continue

            rec = BeliefRecord(
                kind=BaseKind.belief_record,
                created_at=datetime.now(timezone.utc),
                pred_name=atom.pred,
                pred_arity=len(atom.args),
                args=belief_args,
                b=1.0,
                d=0.0,
            )
            key = (rec.pred_name, rec.pred_arity)
            fact_index.setdefault(key, []).append(rec)


def _aggregate_answers_from_evidence(
    rows: Sequence[_EvidenceRow],
    query: Query,
    query_vars: Set[str],
) -> List[QueryAnswer]:
    grouped: Dict[Tuple[Tuple[str, Any], ...], List[_EvidenceRow]] = {}

    for row in rows:
        bindings = _project_bindings(row.subst, query_vars)
        key = tuple(sorted(bindings.items(), key=lambda kv: kv[0]))
        grouped.setdefault(key, []).append(row)

    answers: List[QueryAnswer] = []
    for items, group in grouped.items():
        bindings = dict(items)
        b = _aggregate_values([r.b for r in group], query)
        d = _aggregate_values([r.d for r in group], query)
        answers.append(
            QueryAnswer(
                bindings=bindings,
                b=b,
                d=d,
                belnap_status=_derive_belnap_status(b, d, query),
            )
        )

    return answers


def _aggregate_answers_from_truth(
    rows: Sequence[_TruthRow],
    query: Query,
    query_vars: Set[str],
) -> List[QueryAnswer]:
    grouped: Dict[Tuple[Tuple[str, Any], ...], List[_TruthRow]] = {}

    for row in rows:
        bindings = _project_bindings(row.subst, query_vars)
        key = tuple(sorted(bindings.items(), key=lambda kv: kv[0]))
        grouped.setdefault(key, []).append(row)

    answers: List[QueryAnswer] = []
    for items, group in grouped.items():
        bindings = dict(items)
        b = _aggregate_values([r.support for r in group], query)
        d = _aggregate_values([r.falsity for r in group], query)

        answers.append(
            QueryAnswer(
                bindings=bindings,
                b=b,
                d=d,
                belnap_status=_derive_belnap_status(b, d, query),
            )
        )

    return answers


def _sort_answers(answers: List[QueryAnswer], order_by: List[str]) -> List[QueryAnswer]:
    return sort_answers(answers, order_by)


def _apply_focus(answers: List[QueryAnswer], focus: QueryFocus) -> List[QueryAnswer]:
    return apply_focus(answers, focus)
