"""AUTOGENERATED from doxa/query/evaluator.py during refactoring."""

from __future__ import annotations

import operator
from datetime import date, datetime, timedelta
from typing import (
    Any,
    Dict,
    Iterator,
    Optional,
    Union,
)

from doxa.core.builtins import Builtin
from doxa.query._types import (
    Subst,
    _BuiltinGoal,
    _GroundTerm,
    _Term,
    _VarTerm,
)
from doxa.query._unification import _resolve, _unify

_CMP_OPS: Dict[Builtin, Any] = {
    Builtin.ne: operator.ne,
    Builtin.lt: operator.lt,
    Builtin.leq: operator.le,
    Builtin.gt: operator.gt,
    Builtin.geq: operator.ge,
}

# ---------------------------------------------------------------------------
# Builtins
# ---------------------------------------------------------------------------


def _numeric(val: Any) -> Optional[float]:
    if isinstance(val, (int, float)) and not isinstance(val, bool):
        return float(val)
    return None


def _to_number(v: float) -> Union[int, float]:
    if abs(v - round(v)) <= 1e-9:
        return int(round(v))
    return v


def _temporal_arith(
    op: Builtin,
    a_val: Any,
    b_val: Any,
    c_val: Any,
    a_term: _Term,
    b_term: _Term,
    c_term: _Term,
    subst: Subst,
) -> Optional[Iterator[Subst]]:
    """Try temporal arithmetic. Returns an iterator of substitutions if handled, None if not temporal."""

    def _is_temporal(v: Any) -> bool:
        return isinstance(v, (date, datetime, timedelta))

    resolved = [v for v in (a_val, b_val, c_val) if v is not None]
    if not any(_is_temporal(v) for v in resolved):
        return None  # not temporal, fall through to numeric

    def _yield_result(result: Any, target_term: _Term, s: Subst) -> Iterator[Subst]:
        if isinstance(target_term, _VarTerm):
            new_subst = _unify(target_term, result, s)
            if new_subst is not None:
                yield new_subst
        elif isinstance(target_term, _GroundTerm):
            if target_term.value == result:
                yield s

    # All three bound: verify
    if a_val is not None and b_val is not None and c_val is not None:
        try:
            if op == Builtin.add:
                expected = a_val + b_val
            elif op == Builtin.sub:
                expected = a_val - b_val
            else:
                return iter(())  # mul/div not supported for temporal
            if expected == c_val:
                return iter((subst,))
            return iter(())
        except TypeError:
            return iter(())

    # Two bound, one unbound
    if a_val is not None and b_val is not None and c_val is None:
        try:
            if op == Builtin.add:
                result = a_val + b_val
            elif op == Builtin.sub:
                result = a_val - b_val
            else:
                return iter(())
            return _yield_result(result, c_term, subst)
        except TypeError:
            return iter(())

    if a_val is None and b_val is not None and c_val is not None:
        try:
            if op == Builtin.add:
                result = c_val - b_val  # a = c - b
            elif op == Builtin.sub:
                result = c_val + b_val  # a - b = c => a = c + b
            else:
                return iter(())
            return _yield_result(result, a_term, subst)
        except TypeError:
            return iter(())

    if a_val is not None and b_val is None and c_val is not None:
        try:
            if op == Builtin.add:
                result = c_val - a_val  # b = c - a
            elif op == Builtin.sub:
                result = a_val - c_val  # a - b = c => b = a - c
            else:
                return iter(())
            return _yield_result(result, b_term, subst)
        except TypeError:
            return iter(())

    return iter(())  # too many unbound


def _arith_forward(op: Builtin, a: float, b: float) -> Optional[float]:
    if op == Builtin.add:
        return a + b
    if op == Builtin.sub:
        return a - b
    if op == Builtin.mul:
        return a * b
    if op == Builtin.div:
        return None if abs(b) <= 1e-12 else a / b
    return None


def _arith_solve_a(op: Builtin, b: float, c: float) -> Optional[float]:
    if op == Builtin.add:
        return c - b
    if op == Builtin.sub:
        return c + b
    if op == Builtin.mul:
        return None if abs(b) <= 1e-12 else c / b
    if op == Builtin.div:
        return c * b
    return None


def _arith_solve_b(op: Builtin, a: float, c: float) -> Optional[float]:
    if op == Builtin.add:
        return c - a
    if op == Builtin.sub:
        return a - c
    if op == Builtin.mul:
        return None if abs(a) <= 1e-12 else c / a
    if op == Builtin.div:
        return None if abs(c) <= 1e-12 else a / c
    return None


def _eval_builtin(goal: _BuiltinGoal, subst: Subst) -> Iterator[Subst]:
    op = goal.op

    if op == Builtin.eq:
        a_term, b_term = goal.args
        a_val = _resolve(a_term, subst)
        b_val = _resolve(b_term, subst)

        if a_val is not None and b_val is not None:
            if a_val == b_val:
                yield subst
            return

        if a_val is None and isinstance(a_term, _VarTerm) and b_val is not None:
            new_subst = _unify(a_term, b_val, subst)
            if new_subst is not None:
                yield new_subst
            return

        if b_val is None and isinstance(b_term, _VarTerm) and a_val is not None:
            new_subst = _unify(b_term, a_val, subst)
            if new_subst is not None:
                yield new_subst
            return

        if (
            isinstance(a_term, _VarTerm)
            and isinstance(b_term, _VarTerm)
            and a_term.name == b_term.name
        ):
            yield subst
        return

    if op in (Builtin.add, Builtin.sub, Builtin.mul, Builtin.div):
        a_term, b_term, c_term = goal.args
        a_val = _resolve(a_term, subst)
        b_val = _resolve(b_term, subst)
        c_val = _resolve(c_term, subst)

        # Try temporal arithmetic first; falls through to numeric if not temporal.
        temporal_result = _temporal_arith(
            op,
            a_val,
            b_val,
            c_val,
            a_term,
            b_term,
            c_term,
            subst,
        )
        if temporal_result is not None:
            yield from temporal_result
            return

        na = _numeric(a_val)
        nb = _numeric(b_val)
        nc = _numeric(c_val)

        unbound = sum(1 for n in (na, nb, nc) if n is None)

        if unbound == 0:
            result = _arith_forward(op, na, nb)  # type: ignore[arg-type]
            if result is not None and abs(result - nc) <= 1e-9:  # type: ignore[operator]
                yield subst
            return

        if unbound == 1:
            if nc is None and isinstance(c_term, _VarTerm):
                result = _arith_forward(op, na, nb)  # type: ignore[arg-type]
                if result is not None:
                    new_subst = _unify(c_term, _to_number(result), subst)
                    if new_subst is not None:
                        yield new_subst
                return

            if na is None and isinstance(a_term, _VarTerm):
                result = _arith_solve_a(op, nb, nc)  # type: ignore[arg-type]
                if result is not None:
                    new_subst = _unify(a_term, _to_number(result), subst)
                    if new_subst is not None:
                        yield new_subst
                return

            if nb is None and isinstance(b_term, _VarTerm):
                result = _arith_solve_b(op, na, nc)  # type: ignore[arg-type]
                if result is not None:
                    new_subst = _unify(b_term, _to_number(result), subst)
                    if new_subst is not None:
                        yield new_subst
                return

        return

    if op == Builtin.between:
        x_val = _numeric(_resolve(goal.args[0], subst))
        lo_val = _numeric(_resolve(goal.args[1], subst))
        hi_val = _numeric(_resolve(goal.args[2], subst))
        if (
            x_val is not None
            and lo_val is not None
            and hi_val is not None
            and lo_val <= x_val <= hi_val
        ):
            yield subst
        return

    if op in (
        Builtin.int,
        Builtin.string,
        Builtin.float,
        Builtin.entity,
        Builtin.predicate_ref,
        Builtin.date,
        Builtin.datetime,
        Builtin.duration,
    ):
        val = _resolve(goal.args[0], subst)
        if val is None:
            return

        if op == Builtin.int and isinstance(val, int) and not isinstance(val, bool):
            yield subst
            return
        if op == Builtin.string and isinstance(val, str):
            yield subst
            return
        if op == Builtin.float and isinstance(val, float):
            yield subst
            return
        if op == Builtin.entity and isinstance(val, str):
            yield subst
            return
        if op == Builtin.predicate_ref and isinstance(val, str):
            yield subst
            return
        if (
            op == Builtin.date
            and isinstance(val, date)
            and not isinstance(val, datetime)
        ):
            yield subst
            return
        if op == Builtin.datetime and isinstance(val, datetime):
            yield subst
            return
        if op == Builtin.duration and isinstance(val, timedelta):
            yield subst
            return
        return

    a_val = _resolve(goal.args[0], subst)
    b_val = _resolve(goal.args[1], subst)
    if a_val is None or b_val is None:
        return

    op_fn = _CMP_OPS[op]
    try:
        if op_fn(a_val, b_val):
            yield subst
    except TypeError:
        return
