"""AUTOGENERATED from doxa/query/evaluator.py during refactoring."""

from __future__ import annotations

from typing import (
    Sequence,
)

from doxa.core.epistemic_semantics import (
    BelnapStatusSemantics,
    BodyFalsitySemantics,
    BodyTruthSemantics,
    ConstraintApplicabilitySemantics,
    RuleApplicabilitySemantics,
    SupportAggregationSemantics,
)
from doxa.core.query import Query
from doxa.query.engine import (
    BelnapStatus,
)

# ---------------------------------------------------------------------------
# Epistemic semantics helpers
# ---------------------------------------------------------------------------


def _combine_truth(lhs: float, rhs: float, query: Query) -> float:
    semantics = query.options.epistemic_semantics.body_truth
    if semantics == BodyTruthSemantics.product:
        return lhs * rhs
    if semantics == BodyTruthSemantics.minimum:
        return min(lhs, rhs)
    raise ValueError(f"Unsupported body truth semantics: {semantics!r}")


def _combine_falsity(lhs: float, rhs: float, query: Query) -> float:
    semantics = query.options.epistemic_semantics.body_falsity
    if semantics == BodyFalsitySemantics.noisy_or:
        return 1.0 - ((1.0 - lhs) * (1.0 - rhs))
    if semantics == BodyFalsitySemantics.maximum:
        return max(lhs, rhs)
    raise ValueError(f"Unsupported body falsity semantics: {semantics!r}")


def _rule_applicability(body_b: float, body_d: float, query: Query) -> float:
    semantics = query.options.epistemic_semantics.rule_applicability
    if semantics == RuleApplicabilitySemantics.body_truth_only:
        return body_b
    if semantics == RuleApplicabilitySemantics.body_truth_discounted_by_body_falsity:
        return body_b * (1.0 - body_d)
    raise ValueError(f"Unsupported rule applicability semantics: {semantics!r}")


def _constraint_applicability(body_b: float, body_d: float, query: Query) -> float:
    semantics = query.options.epistemic_semantics.constraint_applicability
    if semantics == ConstraintApplicabilitySemantics.body_truth_only:
        return body_b
    if (
        semantics
        == ConstraintApplicabilitySemantics.body_truth_discounted_by_body_falsity
    ):
        return body_b * (1.0 - body_d)
    raise ValueError(f"Unsupported constraint applicability semantics: {semantics!r}")


def _aggregate_values(values: Sequence[float], query: Query) -> float:
    semantics = query.options.epistemic_semantics.support_aggregation
    vals = [float(v) for v in values if v > 0.0]
    if not vals:
        return 0.0

    if semantics == SupportAggregationSemantics.noisy_or:
        prod = 1.0
        for v in vals:
            prod *= 1.0 - v
        return 1.0 - prod

    if semantics == SupportAggregationSemantics.maximum:
        return max(vals)

    if semantics == SupportAggregationSemantics.capped_sum:
        return min(1.0, sum(vals))

    raise ValueError(f"Unsupported support aggregation semantics: {semantics!r}")


def _derive_belnap_status(b: float, d: float, query: Query) -> BelnapStatus:
    semantics = query.options.epistemic_semantics.belnap_status
    if semantics != BelnapStatusSemantics.nonzero:
        raise ValueError(f"Unsupported Belnap status semantics: {semantics!r}")

    eps = 1e-12
    has_b = b > eps
    has_d = d > eps

    if has_b and has_d:
        return BelnapStatus.both
    if has_b:
        return BelnapStatus.true
    if has_d:
        return BelnapStatus.false
    return BelnapStatus.neither
