"""AUTOGENERATED from doxa/query/evaluator.py during refactoring."""

from __future__ import annotations

from typing import (
    Any,
    Dict,
    Iterator,
    List,
    Optional,
    Sequence,
    Set,
    Tuple,
)

from doxa.core.epistemic_semantics import (
    ConstraintPropagationSemantics,
    NonAtomSemantics,
    RulePropagationSemantics,
)
from doxa.core.query import Query
from doxa.query._builtins import _eval_builtin
from doxa.query._compilation import _compile_constraint_body, _get_compiled_rule
from doxa.query._epistemic import (
    _aggregate_values,
    _combine_falsity,
    _combine_truth,
    _constraint_applicability,
    _rule_applicability,
)
from doxa.query._types import (
    _FREE,
    CallPatternKey,
    ExplainCollector,
    GroundAtomKey,
    Subst,
    _AssumeGoal,
    _Atom,
    _BuiltinGoal,
    _Context,
    _EvidenceRow,
    _Goal,
    _MemoEvidenceRow,
    _TruthRow,
)
from doxa.query._unification import (
    _belief_arg_value,
    _ground_atom_key,
    _match_rule_head,
    _resolve,
    _unify,
)

# ---------------------------------------------------------------------------
# Evidence solving
# ---------------------------------------------------------------------------


def _aggregate_evidence_rows(
    rows: Sequence[_EvidenceRow],
    query: Query,
) -> List[_EvidenceRow]:
    grouped: Dict[Tuple[Tuple[str, Any], ...], List[_EvidenceRow]] = {}
    for row in rows:
        key = tuple(sorted(row.subst.items(), key=lambda kv: kv[0]))
        grouped.setdefault(key, []).append(row)

    out: List[_EvidenceRow] = []
    for items, group in grouped.items():
        subst = dict(items)
        b = _aggregate_values([r.b for r in group], query)
        d = _aggregate_values([r.d for r in group], query)
        out.append(_EvidenceRow(subst=subst, b=b, d=d))
    return out


def _replay_memoized_evidence(
    goal: _Atom,
    subst: Subst,
    rows: Sequence[_MemoEvidenceRow],
) -> List[_EvidenceRow]:
    replayed: List[_EvidenceRow] = []
    for row in rows:
        new_subst: Optional[Subst] = subst
        for term, value in zip(goal.args, row.args):
            new_subst = _unify(term, value, new_subst)  # type: ignore[arg-type]
            if new_subst is None:
                break
        if new_subst is not None:
            replayed.append(_EvidenceRow(subst=new_subst, b=row.b, d=row.d))
    return replayed


def _memoize_evidence_rows(
    goal: _Atom,
    rows: Sequence[_EvidenceRow],
) -> List[_MemoEvidenceRow]:
    memo_rows: List[_MemoEvidenceRow] = []
    seen: Set[Tuple[Tuple[Any, ...], float, float]] = set()
    for row in rows:
        grounded = _ground_atom_key(goal, row.subst)
        if grounded is None:
            continue
        key = (grounded[1], row.b, row.d)
        if key in seen:
            continue
        seen.add(key)
        memo_rows.append(_MemoEvidenceRow(args=grounded[1], b=row.b, d=row.d))
    return memo_rows


def _positive_atom_evidence(
    goal: _Atom,
    subst: Subst,
    ctx: _Context,
    collector: Optional[ExplainCollector],
    depth: int,
) -> List[_EvidenceRow]:
    if depth > ctx.max_depth:
        return []

    # --- Tabling: resolve args to build call-pattern key --------------------
    resolved = tuple(_resolve(a, subst) for a in goal.args)
    call_key: CallPatternKey = (
        goal.pred,
        tuple(v if v is not None else _FREE for v in resolved),
    )

    # Cycle detection (ground AND non-ground call patterns)
    if call_key in ctx.in_progress:
        return []

    # Memoisation hit for this call pattern.
    memo_rows = ctx.memo.get(call_key)
    if memo_rows is not None:
        return _replay_memoized_evidence(goal, subst, memo_rows)

    ctx.in_progress.add(call_key)

    # --- Normal evaluation -------------------------------------------------
    rows: List[_EvidenceRow] = []

    # facts
    for record in ctx.fact_index.get((goal.pred, len(goal.args)), ()):
        new_subst: Optional[Subst] = subst
        for g_term, f_arg in zip(goal.args, record.args):
            new_subst = _unify(g_term, _belief_arg_value(f_arg), new_subst)  # type: ignore[arg-type]
            if new_subst is None:
                break

        if new_subst is not None:
            if collector is not None:
                collector.record(
                    "fact_support",
                    {
                        "pred": goal.pred,
                        "b": record.b,
                        "d": record.d,
                    },
                )
            rows.append(_EvidenceRow(subst=new_subst, b=record.b, d=record.d))

    # rules
    for rule_idx, rule in ctx.rules_by_head.get((goal.pred, len(goal.args)), ()):
        compiled_rule = _get_compiled_rule(ctx, rule_idx, rule, depth)
        match = _match_rule_head(compiled_rule.head_terms, goal.args, subst)
        if match is None:
            continue

        new_query_subst, initial_rule_subst, links = match
        for body_row in _solve_body_truth(
            compiled_rule.body_goals,
            initial_rule_subst,
            ctx,
            collector,
            depth + 1,
            current_support=1.0,
            current_falsity=0.0,
        ):
            result_subst = dict(new_query_subst)
            conflict = False
            for q_var, r_var in links:
                if r_var in body_row.subst:
                    value = body_row.subst[r_var]
                    if q_var in result_subst and result_subst[q_var] != value:
                        conflict = True
                        break
                    result_subst[q_var] = value
            if conflict:
                continue

            applicability = _rule_applicability(
                body_row.support,
                body_row.falsity,
                ctx.query,
            )
            if applicability <= 0.0:
                continue

            if collector is not None:
                collector.record(
                    "rule_applicability",
                    {
                        "pred": goal.pred,
                        "rule_head": rule.head_pred_name,
                        "body_support": body_row.support,
                        "body_falsity": body_row.falsity,
                        "applicability": applicability,
                    },
                )

            propagation = ctx.query.options.epistemic_semantics.rule_propagation
            if propagation != RulePropagationSemantics.body_times_rule_weights:
                raise ValueError(
                    f"Unsupported rule propagation semantics: {propagation!r}"
                )

            b = applicability * rule.b
            d = applicability * rule.d

            if collector is not None:
                collector.record(
                    "rule_support",
                    {
                        "pred": goal.pred,
                        "rule_head": rule.head_pred_name,
                        "body_support": body_row.support,
                        "body_falsity": body_row.falsity,
                        "applicability": applicability,
                        "b": b,
                        "d": d,
                    },
                )

            rows.append(_EvidenceRow(subst=result_subst, b=b, d=d))

    result = _aggregate_evidence_rows(rows, ctx.query)

    # --- Tabling: cache result and clear in-progress flag ------------------
    ctx.in_progress.discard(call_key)
    ctx.memo[call_key] = _memoize_evidence_rows(goal, result)

    return result


def _positive_atom_truth_rows(
    goal: _Atom,
    subst: Subst,
    ctx: _Context,
    collector: Optional[ExplainCollector],
    depth: int,
) -> List[_TruthRow]:
    evidence_rows = _positive_atom_evidence(goal, subst, ctx, collector, depth)
    out: List[_TruthRow] = []
    for row in evidence_rows:
        if row.b > 0.0 or row.d > 0.0:
            grounded = _ground_atom_key(goal, row.subst)
            atoms: Tuple[GroundAtomKey, ...] = (
                (grounded,) if grounded is not None else ()
            )
            out.append(
                _TruthRow(
                    subst=row.subst,
                    support=row.b,
                    falsity=row.d,
                    atoms=atoms,
                )
            )
    return out


def _constraint_violation_for_atoms(
    atoms: Tuple[GroundAtomKey, ...],
    ctx: _Context,
    collector: Optional[ExplainCollector],
    depth: int,
) -> float:
    if not atoms or not ctx.constraints:
        return 0.0

    atom_set = set(atoms)
    violations: List[float] = []

    for idx, constraint in enumerate(ctx.constraints):
        prefix = f"_c{depth}_{idx}_"
        body_goals = _compile_constraint_body(constraint, prefix)

        for body_row in _solve_body_truth(
            body_goals,
            {},
            ctx,
            collector,
            depth=depth + 1,
            current_support=1.0,
            current_falsity=0.0,
            current_atoms=(),
            apply_constraints=False,
        ):
            if not body_row.atoms:
                continue

            # Constraint only applies to this derivation if all grounded atoms
            # used by the constraint are contained in the derivation footprint.
            if not set(body_row.atoms).issubset(atom_set):
                continue

            applicability = _constraint_applicability(
                body_row.support,
                body_row.falsity,
                ctx.query,
            )
            if applicability <= 0.0:
                continue

            propagation = ctx.query.options.epistemic_semantics.constraint_propagation
            if (
                propagation
                != ConstraintPropagationSemantics.body_times_constraint_weights_to_violation
            ):
                raise ValueError(
                    f"Unsupported constraint propagation semantics: {propagation!r}"
                )

            violations.append(applicability * constraint.b)

    return _aggregate_values(violations, ctx.query)


def _solve_body_truth(
    goals: Sequence[_Goal],
    subst: Subst,
    ctx: _Context,
    collector: Optional[ExplainCollector],
    depth: int,
    current_support: float,
    current_falsity: float,
    current_atoms: Tuple[GroundAtomKey, ...] = (),
    apply_constraints: bool = True,
) -> Iterator[_TruthRow]:
    if depth > ctx.max_depth:
        return

    if not goals:
        final_falsity = current_falsity

        if apply_constraints:
            violation = _constraint_violation_for_atoms(
                current_atoms,
                ctx,
                collector,
                depth,
            )
            if violation > 0.0:
                final_falsity = _aggregate_values(
                    [final_falsity, violation],
                    ctx.query,
                )

        yield _TruthRow(
            subst=subst,
            support=current_support,
            falsity=final_falsity,
            atoms=current_atoms,
        )
        return

    goal = goals[0]
    rest = goals[1:]

    if isinstance(goal, _AssumeGoal):
        # assume(...) always succeeds — it just injects temporary facts.
        # The actual injection is done before solving begins (in _evaluate).
        # At solve time, assume goals are a no-op pass-through.
        yield from _solve_body_truth(
            rest,
            subst,
            ctx,
            collector,
            depth,
            current_support,
            current_falsity,
            current_atoms,
            apply_constraints,
        )
        return

    if isinstance(goal, _BuiltinGoal):
        for new_subst in _eval_builtin(goal, subst):
            yield from _solve_body_truth(
                rest,
                new_subst,
                ctx,
                collector,
                depth,
                current_support,
                current_falsity,
                current_atoms,
                apply_constraints,
            )
        return

    assert isinstance(goal, _Atom)

    if goal.negated:
        positive = _Atom(pred=goal.pred, negated=False, args=goal.args)
        has_any = any(
            row.support > 0.0
            for row in _positive_atom_truth_rows(
                positive,
                subst,
                ctx,
                collector,
                depth + 1,
            )
        )

        non_atom = ctx.query.options.epistemic_semantics.non_atom
        if non_atom != NonAtomSemantics.crisp_filters:
            raise ValueError(f"Unsupported non-atom semantics: {non_atom!r}")

        if not has_any:
            yield from _solve_body_truth(
                rest,
                subst,
                ctx,
                collector,
                depth,
                current_support,
                current_falsity,
                current_atoms,
                apply_constraints,
            )
        return

    for atom_row in _positive_atom_truth_rows(goal, subst, ctx, collector, depth):
        combined_support = _combine_truth(
            current_support,
            atom_row.support,
            ctx.query,
        )
        combined_falsity = _combine_falsity(
            current_falsity,
            atom_row.falsity,
            ctx.query,
        )
        yield from _solve_body_truth(
            rest,
            atom_row.subst,
            ctx,
            collector,
            depth,
            combined_support,
            combined_falsity,
            current_atoms + atom_row.atoms,
            apply_constraints,
        )
