"""AUTOGENERATED from doxa/query/evaluator.py during refactoring."""

from __future__ import annotations

from typing import (
    Any,
    List,
    Mapping,
    Optional,
    Tuple,
)

from doxa.core.belief_record import (
    BeliefArg,
    BeliefEntityArg,
    BeliefLiteralArg,
)
from doxa.query._types import (
    GroundAtomKey,
    Subst,
    _Atom,
    _GroundTerm,
    _Term,
    _VarTerm,
)

# ---------------------------------------------------------------------------
# Basic substitution / matching
# ---------------------------------------------------------------------------


def _resolve(term: _Term, subst: Subst) -> Optional[Any]:
    if isinstance(term, _GroundTerm):
        return term.value
    return subst.get(term.name)


def _unify(term: _Term, value: Any, subst: Subst) -> Optional[Subst]:
    if isinstance(term, _GroundTerm):
        return subst if term.value == value else None

    if term.name in subst:
        return subst if subst[term.name] == value else None

    return {**subst, term.name: value}


def _belief_arg_value(arg: BeliefArg) -> Any:
    if isinstance(arg, BeliefEntityArg):
        return arg.ent_name
    if isinstance(arg, BeliefLiteralArg):
        return arg.value
    if hasattr(arg, "pred_ref_name"):
        return f"{arg.pred_ref_name}/{arg.pred_ref_arity}"
    raise TypeError(f"Unsupported belief arg type: {type(arg)!r}")


def _ground_atom_key(atom: _Atom, subst: Mapping[str, Any]) -> Optional[GroundAtomKey]:
    values: List[Any] = []
    for arg in atom.args:
        value = _resolve(arg, dict(subst))
        if value is None:
            return None
        values.append(value)
    return atom.pred, tuple(values)


def _match_rule_head(
    head_terms: Tuple[_Term, ...],
    goal_args: Tuple[_Term, ...],
    query_subst: Subst,
) -> Optional[Tuple[Subst, Subst, List[Tuple[str, str]]]]:
    """
    Match a compiled rule head against a compiled goal under the current query subst.

    Returns:
      (new_query_subst, initial_rule_subst, links)
    where links maps (query_var_name, rule_var_name).
    """
    new_q = dict(query_subst)
    r_subst: Subst = {}
    links: List[Tuple[str, str]] = []

    for h_term, g_term in zip(head_terms, goal_args):
        g_val = _resolve(g_term, new_q)

        if isinstance(h_term, _GroundTerm):
            if g_val is not None:
                if h_term.value != g_val:
                    return None
            else:
                if isinstance(g_term, _VarTerm):
                    if g_term.name in new_q and new_q[g_term.name] != h_term.value:
                        return None
                    new_q[g_term.name] = h_term.value
        else:
            if g_val is not None:
                if h_term.name in r_subst and r_subst[h_term.name] != g_val:
                    return None
                r_subst[h_term.name] = g_val
            else:
                if isinstance(g_term, _VarTerm):
                    links.append((g_term.name, h_term.name))

    return new_q, r_subst, links
